// <auto-generated />
using System;
using InteractiveMap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractiveMap.Migrations
{
    [DbContext(typeof(InteractiveMapContext))]
    [Migration("20221122212527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InteractiveMap.Models.Audience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SvgCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string?>("aud")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("imgWay")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("imgSvg")
                        .HasColumnType("nvarchar(50)");
                    b.HasKey("Id");

                    b.ToTable("Audience");
                });
#pragma warning restore 612, 618
        }
    }
}
